-   repo: git@github.com:pre-commit/pre-commit-hooks
    sha: v0.7.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: debug-statements
    -   id: flake8
        args:
        - --max-line-length=99
    -   id: check-added-large-files
-   repo: git://github.com/FalconSocial/pre-commit-mirrors-pep257
    sha: f464d46624a959c6969ce6bcf2cd531cdeefb85a
    hooks:
    -   id: pep257
        args:
        - --ignore=D100,D101,D102,D103,D104,D105,D203
-   repo: git://github.com/FalconSocial/pre-commit-python-sorter
    sha: b57843b0b874df1d16eb0bef00b868792cb245c2
    hooks:
    -   id: python-import-sorter
        language: system
